---
- hosts: nodes
  remote_user: root
  tasks:
    - name: check inventory
      debug:
        msg: "{{ hostvars }}"
      check_mode: yes
    - include_tasks: roles.yml
      vars:
        - user_home: /home/{{ user.name }}
        - user_profile: ".{{ user.name }}.common.profile"
      loop: "{{ users }}"
      loop_control:
        loop_var: user
      tags: always
