---
- hosts: nodes
  remote_user: root
  tasks:
    - name: check inventory
      tags: debug
      debug:
        msg: "{{ hostvars }}"
    - include_tasks: roles.yml
      tags: always
      loop: "{{ users }}"
      loop_control:
        loop_var: user
      vars:
        home_dir:
          Darwin: /Users
          Debian: /home
          RedHat: /home
        user_home: "{{ home_dir[ansible_os_family] }}/{{ user.name }}"
        user_profile: ".{{ user.name }}.custom.profile"
