---
- name: setup pip config directory
  become: yes
  become_user: "{{ user.name }}"
  file:
    path: "{{ user_home }}/.config/pip"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"

- name: create pip profile {{ user_home }}/.config/pip/pip.conf
  become: yes
  become_user: "{{ user.name }}"
  file:
    path: "{{ user_home }}/.config/pip/pip.conf"
    state: touch
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0644"
    modification_time: preserve
    access_time: preserve

- name: setup pip profile for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/.config/pip/pip.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK user_setup/{{ role_name }}/setup_pip_config"
    block: |
      [global]
      index-url = https://pypi.tuna.tsinghua.edu.cn/simple

- name: get miniconda3 installer under {{ user_home }}
  tags: pro
  become: yes
  become_user: "{{ user.name }}"
  vars:
    - conda_url:
        x86_64:
          Debian: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          RedHat: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          Darwin: https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        aarch64:
          Debian: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh
          RedHat: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh
  get_url:
    url: "{{ conda_url[ansible_architecture][ansible_os_family] }}"
    dest: "{{ user_home }}/.miniconda3.installer.sh"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"

- name: install miniconda3 for {{ user.name }}
  tags: pro
  become: yes
  become_user: "{{ user.name }}"
  shell:
    cmd: "{{ user_home }}/.miniconda3.installer.sh -b -p {{ user_home }}/.conda/3.x"
    chdir: "{{ user_home }}"
    creates: "{{ user_home }}/.conda/3.x"

- name: create conda profile {{ user_home }}/.condarc
  tags: pro
  become: yes
  become_user: "{{ user.name }}"
  file:
    path: "{{ user_home }}/.condarc"
    state: touch
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0644"
    modification_time: preserve
    access_time: preserve

- name: setup conda profile for {{ user.name }}
  tags: pro
  become: yes
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/.condarc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK user_setup/{{ role_name }}/setup_miniconda_config"
    block: |
      auto_activate_base: false
      show_channel_urls: true
      channels:
        - tuna
        - defaults
      custom_multichannels:
        tuna:
          - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
          - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
          - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
      custom_channels:
        conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
        msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
        bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
        menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
        pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
        simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
