---
- name: install zsh via brew
  become: true
  become_user: "{{ user.name }}"
  when: ansible_pkg_mgr == 'homebrew'
  homebrew:
    name: zsh
    state: present

- name: install zsh
  become: true
  when: ansible_pkg_mgr != 'homebrew'
  package:
    name: zsh
    state: present

- name: get zsh config installer in {{ user_home }}
  tags: pro
  become: true
  become_user: "{{ user.name }}"
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ user_home }}/.oh-my-zsh.installer.sh"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"

- name: setup zsh config for {{ user.name }}
  tags: pro
  become: true
  become_user: "{{ user.name }}"
  shell:
    cmd: "{{ user_home }}/.oh-my-zsh.installer.sh --unattended"
    chdir: "{{ user_home }}"
    creates: "{{ user_home }}/.oh-my-zsh"

- name: include {{ user_profile }} into {{ user_home }}/.zshrc
  tags: pro
  become: true
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK user_setup/{{ role_name }}"
    block: |
      source {{ user_home }}/{{ user_profile }}

- name: setup {{ user.name }}'s login shell when use brew
  when: ansible_pkg_mgr == 'homebrew'
  become: true
  user:
    name: "{{ user.name }}"
    shell: /usr/local/bin/zsh

- name: setup {{ user.name }}'s login shell
  when: ansible_pkg_mgr != 'homebrew'
  become: true
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
