---
- name: install tmux via brew
  when: ansible_pkg_mgr == 'homebrew'
  become: true
  become_user: "{{ user.name }}"
  homebrew:
    name: tmux
    state: present

- name: install requirements for tmux config via brew
  tags: pro
  when: ansible_pkg_mgr == 'homebrew'
  become: true
  become_user: "{{ user.name }}"
  homebrew:
    name:
      - perl
      - awk
      - xsel
      - xclip
    state: present

- name: setup perl
  when: ansible_pkg_mgr == 'homebrew'
  become: true
  become_user: "{{ user.name }}"
  shell:
    cmd: 'PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib'

- name: set perl shell config
  when: ansible_pkg_mgr == 'homebrew'
  become: true
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/{{ user_profile }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK user_setup/{{ role_name }}/setup_perl"
    block: |
      eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"

- name: install tmux
  when: ansible_pkg_mgr != 'homebrew'
  become: true
  package:
    name: tmux
    state: present

- name: install requirements for tmux config
  tags: pro
  when: ansible_pkg_mgr != 'homebrew'
  become: true
  package:
    name:
      - perl
      - sed
      - xsel
      - xclip
    state: present

- name: pull tmux config in {{ user.name }}
  tags: pro
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: "https://github.com/gpakosz/.tmux.git"
    dest: "{{ user_home }}/.tmux"
    update: no

- name: setup tmux config for {{ user.name }}
  tags: pro
  become: true
  become_user: "{{ user.name }}"
  file:
    state: link
    src: "{{ user_home }}/.tmux/.tmux.conf"
    path: "{{ user_home }}/.tmux.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: prepare for tmux config custom by {{ user.name }}
  tags: pro
  become: true
  become_user: "{{ user.name }}"
  copy:
    remote_src: yes
    src: "{{ user_home }}/.tmux/.tmux.conf.local"
    dest: "{{ user_home }}/.tmux.conf.local"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0644"
    force: no

- name: custom tmux config for {{ user.name }}
  tags: pro
  become: true
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/.tmux.conf.local"
    marker: "# {mark} ANSIBLE MANAGED BLOCK user_setup/{{ role_name }}"
    block: |
      set -gu prefix2
      unbind C-a
      unbind C-b
      set -g prefix C-s
      bind C-s send-prefix
      set -g mouse on
      tmux_conf_copy_to_os_clipboard=true
      tmux_conf_new_pane_reconnect_ssh=true
      tmux_conf_theme_highlight_focused_pane=true
