---
- name: install docker via brew cask
  when: ansible_pkg_mgr == 'homebrew'
  become: true
  become_user: "{{ user.name }}"
  homebrew_cask:
    name: docker
    state: present

- name: install {{ docker_pkg_name[ansible_distribution] }} for {{ ansible_distribution }}
  when: ansible_pkg_mgr != 'homebrew'
  become: true
  vars:
    docker_pkg_name:
      Debian: docker.io
      RedHat: docker.ce
  package:
    name: "{{ docker_pkg_name[ansible_os_family] }}"
    state: present

- name: add user {{ user.name }} in docker group
  when: ansible_os_family != 'Darwin'
  become: true
  user:
    name: "{{ user.name }}"
    append: yes
    groups: [docker]
