---

- name: install vim via brew
  when: ansible_pkg_mgr == 'homebrew'
  become: yes
  become_user: "{{ user.name }}"
  homebrew:
    name: vim
    state: present

- name: install vim
  when: ansible_pkg_mgr != 'homebrew'
  become: yes
  package:
    name: vim
    state: present

- name: setup vim env for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/{{ user_profile }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK user_setup/{{ role_name }}"
    block: |
      export EDITOR=vim

- name: get vim config installer in {{ user_home }}
  tags: pro
  become: yes
  become_user: "{{ user.name }}"
  get_url:
    url: https://spacevim.org/install.sh
    dest: "{{ user_home }}/.space-vim.installer.sh"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'

- name: setup vim config for {{ user.name }}
  tags: pro
  become: yes
  become_user: "{{ user.name }}"
  shell:
    cmd: "{{ user_home }}/.space-vim.installer.sh"
    chdir: "{{ user_home }}"
    creates: "{{ user_home }}/.SpaceVim"
